db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=jupiter
    - POSTGRES_USER=jupiter
    - PGPORT=6000
  ports:
    - "6000:6000"


scoring:
  image: jupiterapp/scoring
  ports:
    - "8001:8001"
  volumes:
    - ./services/scoring:/scoring


backend:
  image: jupiterapp/backend
  privileged: true
  ports:
    - "8000:8000"
  volumes:
    - ./services/backend:/backend
  environment:
    - DB_PASSWORD=jupiter
    - DB_USER=jupiter
    - DB_HOST=db
    - DB_PORT=6000
    - SCORING_HOST=scoring
    - SCORING_PORT=8001
    - MIGRATE=true
    - COLLECTSTATIC=true
    - TEST=false
    - RUNSERVER=false
    - SLEEP=true
    - SENDGRID_TOKEN=U0cuT0xoRXBNd3JSOGVJcVFJUG05MjItQS44RllmSWhnV19EbFRTUk4wRkw5QTZBUUMxWXFhbkF4eDA0ZW1DU25rc293
    - SITE_HOST = http://localhost/
  links:
    - db:db
    - scoring:scoring


frontend:
  image: jupiterapp/frontend
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./services/frontend/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    - ./services/frontend/nginx/conf.d/:/etc/nginx/conf.d/
    - ./services/frontend/app/src:/frontend/app/src
    - ./services/frontend/app/index.html:/frontend/app/index.html
    - ./services/frontend/app/favicon.ico:/frontend/app/favicon.ico
    - ./services/frontend/app/assets/:/frontend/app/assets/
    - ./services/frontend/app/package.json:/frontend/app/package.json
  links:
    - backend:backend
