db:
  image: postgres
  environment:
    - POSTGRES_PASSWORD=jupiter
    - POSTGRES_USER=jupiter
    - PGPORT=6000


scoring:
  image: bor1senko/scoring


backend:
  image: bor1senko/backend
  privileged: true
  ports:
    - "8000:8000"
  environment:
    - DB_PASSWORD=jupiter
    - DB_USER=jupiter
    - DB_HOST=db
    - DB_PORT=6000
    - SCORING_HOST=scoring
    - SCORING_PORT=8001
    - SENDGRID_TOKEN=U0cuSEtNdUJDbWJTT0NtSUFQR0RLQ1NyQS50OW5NVDE4a0FKT2J4MlBLMDFWSjlEcV96ZDlHOFUtR1gwTWx3TkxQTGZ3
    - SITE_HOST = https://iron-bank.me/
  links:
    - db:db
    - scoring:scoring


frontend:
  image: bor1senko/frontend
  ports:
    - "80:80"
    - "443:443"
  links:
    - backend:backend
  volumes:
    - ./frontend/cert/iron-bank.crt:/etc/ssl/certs/jupiter.cert.pem
    - ./frontend/cert/iron-bank.key:/etc/ssl/certs/jupiter.key.pem
