# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittemplate',
            name='detailed_info',
            field=models.TextField(default='TBD'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deposittemplate',
            name='detailed_info',
            field=models.TextField(default='TBD'),
            preserve_default=False,
        ),
    ]
