# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-25 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20161224_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(101, ''), (102, ''), (103, ''), (104, ''), (105, ''), (106, ''), (107, ''), (108, ''), (201, ''), (202, ''), (203, ''), (204, ''), (205, ''), (206, ''), (207, ''), (208, ''), (209, ''), (210, ''), (201, ''), (202, ''), (203, ''), (204, ''), (205, ''), (206, ''), (207, ''), (208, ''), (209, ''), (210, ''), (666, '')], default=666),
        ),
    ]
