# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_auto_20161225_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed'), (2, 'Disabled'), (3, 'Rejected'), (4, 'Create claim leaved'), (5, 'Close claim leaved')]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed'), (2, 'Rejected'), (3, 'Requested creating'), (4, 'Requested closing')]),
        ),
    ]
