# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_auto_20161226_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittemplate',
            name='type',
            field=models.IntegerField(choices=[(0, 'For own needs'), (1, "On the seller's account")], default=0),
        ),
    ]
