# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_credittemplate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(default='0000000000000', max_length=30),
        ),
    ]
