# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 02:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_auto_20161228_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('view_account', 'Can view account'), ('leave_create_claim_account', 'Can leave create claim'), ('confirm_create_claim_account', 'Can confirm create claim'), ('reject_create_claim_account', 'Can reject create claim'), ('leave_close_claim_account', 'Can leave close claim'), ('confirm_close_claim_account', 'Can confirm close claim'), ('reject_close_claim_account', 'Can reject close claim'), ('assign_account', 'Can assign account')), 'verbose_name': 'Checking account', 'verbose_name_plural': 'Checking accounts'},
        ),
        migrations.AlterModelOptions(
            name='credit',
            options={'permissions': (('view_credit', 'Can view credit'), ('make_payment_credit', 'Can make payment'), ('open_online_credit', 'Can open online'), ('leave_create_claim_credit', 'Can leave craate claim'), ('confirm_create_claim_credit', 'Can confirm create claim'), ('reject_create_claim_credit', 'Can reject create claim'), ('close_credit', 'Can close credit')), 'verbose_name': 'Credit', 'verbose_name_plural': 'Credits'},
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'permissions': (('view_deposit', 'Can view deposit'), ('leave_create_claim_deposit', 'Can leave create claim'), ('confirm_create_claim_deposit', 'Can confirm create claim'), ('reject_create_claim_deposit', 'Can reject create claim'), ('leave_close_claim_deposit', 'Can leave close claim'), ('confirm_close_claim_deposit', 'Can confirm close claim'), ('reject_close_claim_deposit', 'Can reject close claim'), ('put_money_deposit', 'Can put money on deposit')), 'verbose_name': 'Deposit', 'verbose_name_plural': 'Deposits'},
        ),
    ]
