# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '009_financesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financesettings',
            options={'permissions': (('view_financesettings', 'Can view finance settings'),), 'verbose_name': 'Finance settings', 'verbose_name_plural': 'Finance settings'},
        ),
    ]
