# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20161229_0718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'permissions': (('view_account', 'Can view account'), ('leave_create_claim_account', 'Can leave create claim'), ('confirm_create_claim_account', 'Can confirm create claim'), ('reject_create_claim_account', 'Can reject create claim'), ('unassign_account', 'Can unassign account'), ('assign_account', 'Can assign account')), 'verbose_name': 'Checking account', 'verbose_name_plural': 'Checking accounts'},
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Closed'), (2, 'Disabled'), (3, 'Rejected'), (4, 'Create claim leaved')]),
        ),
    ]
