# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 01:36
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20161229_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring', django.contrib.postgres.fields.jsonb.JSONField(default={'danger_level': 0.3, 'warning_level': 0.6})),
                ('currencies', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=['BYN', 'USD', 'EUR', 'RUB'], size=None)),
                ('exchange_rates', django.contrib.postgres.fields.jsonb.JSONField(default={'BYN': 1.0, 'EUR': 2.043, 'RUB': 3.2182, 'USD': 1.9519})),
            ],
        ),
    ]
