# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter_auth', '0004_auto_20161224_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_times_30_59_days_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_of_times_60_89_days_late',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_of_times_90_more_days_late',
            field=models.IntegerField(default=0),
        ),
    ]
