# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 09:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter_auth', '0007_auto_20161229_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_user', 'Can view users'), ('manage_himself', 'Can manage himself'), ('change_password_user', 'Can change password')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
