# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 12:58
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter_auth', '0010_auto_20161229_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that username already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(default=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dependants',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='income',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('1000'), default_currency=b'BYN', max_digits=15),
        ),
    ]
