# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter_auth', '0011_auto_20161230_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_expires',
            field=models.DateField(),
        ),
    ]
