# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-12-03 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jupiter_auth', '0013_userprofile_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAddOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('token', models.TextField(null=True)),
                ('username', models.TextField(default='me', null=True)),
                ('is_superuser', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ServiceAddOn',
                'verbose_name_plural': 'ServiceAddOn',
            },
        ),
    ]
